Rails:
  Enabled: true

AllCops:
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'db/schema.rb'
    - 'features/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.2
  StyleGuideBaseURL: 'https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md'

Encoding:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/LineLength:
  Max: 250
MethodLength:
  Max: 40
Metrics/BlockLength:
  Enabled: false
Documentation:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Style/FileName:
  Enabled: false
Style/ClassAndModuleChildren:
  SupportedStyles: compact
Style/AccessorMethodName:
  Enabled: false
ClassLength:
  Max: 210
PerceivedComplexity:
  Enabled: false
TrivialAccessors:
  Enabled: false
Lint/RescueException:
  Enabled: false
RedundantSelf:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Style/Lambda:
  Enabled: false
AbcSize:
  Enabled: false
Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb # For .change blocks.
MultilineOperationIndentation:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UselessAccessModifier:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Performance/StartWith:
  Enabled: true
Performance/EndWith:
  Enabled: true
Performance/RegexpMatch:
  Enabled: true

# The following should be re-enabled for ruby 3 update
Style/StringLiterals:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Performance/TimesMap:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# These only apply to rails 5 and above
Rails/HttpPositionalArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
